// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectionCreate(arg1) {
  return window['go']['main']['App']['ConnectionCreate'](arg1);
}

export function ConnectionDelete(arg1) {
  return window['go']['main']['App']['ConnectionDelete'](arg1);
}

export function ConnectionEdit(arg1) {
  return window['go']['main']['App']['ConnectionEdit'](arg1);
}

export function ConnectionList(arg1) {
  return window['go']['main']['App']['ConnectionList'](arg1);
}

export function CreateKeyValue(arg1) {
  return window['go']['main']['App']['CreateKeyValue'](arg1);
}

export function DBList(arg1) {
  return window['go']['main']['App']['DBList'](arg1);
}

export function DeleteKeyValue(arg1) {
  return window['go']['main']['App']['DeleteKeyValue'](arg1);
}

export function GetKeyValue(arg1) {
  return window['go']['main']['App']['GetKeyValue'](arg1);
}

export function KeyList(arg1) {
  return window['go']['main']['App']['KeyList'](arg1);
}

export function ListValueCreate(arg1) {
  return window['go']['main']['App']['ListValueCreate'](arg1);
}

export function ListValueDelete(arg1) {
  return window['go']['main']['App']['ListValueDelete'](arg1);
}

export function UpdateKeyValue(arg1) {
  return window['go']['main']['App']['UpdateKeyValue'](arg1);
}
