// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';
import {main} from '../models';

export function ConnectionCreate(arg1:define.Connection):Promise<main.H>;

export function ConnectionDelete(arg1:string):Promise<main.H>;

export function ConnectionEdit(arg1:define.Connection):Promise<main.H>;

export function ConnectionList(arg1:string):Promise<main.H>;

export function CreateKeyValue(arg1:define.CreateKeyValueRequest):Promise<main.H>;

export function DBList(arg1:string):Promise<main.H>;

export function DeleteKeyValue(arg1:define.KeyValueRequest):Promise<main.H>;

export function GetKeyValue(arg1:define.KeyValueRequest):Promise<main.H>;

export function KeyList(arg1:define.KeyListRequest):Promise<main.H>;

export function ListValueCreate(arg1:define.ListValueRequest):Promise<main.H>;

export function ListValueDelete(arg1:define.ListValueRequest):Promise<main.H>;

export function UpdateKeyValue(arg1:define.UpdateKeyValueRequest):Promise<main.H>;
